<?php

declare(strict_types=1);

namespace App\Models;

use App\Domain\Treasury\Enums\AccountChannelType;
use App\Domain\Treasury\Enums\AccountUsage;
use App\Domain\Treasury\Enums\Currency;
use App\Enums\ActiveStatus;
use App\Models\MasterData\Bank;
use App\Models\MasterData\MobileMoneyProvider;
use App\Support\Money;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Backend spec §2.2 — `bank_accounts`.
 *
 * Each one owns exactly one 8xxx chart account, created with it.
 *
 * This used to be read-only — "the frontend has no bank-account CRUD screen
 * (readiness report gap 3), so this is seeded and read, never managed through
 * an endpoint". That gap is closed: Bank → Register Account manages these now,
 * and the four fields that screen collects and this table lacked have been
 * added.
 *
 * `opening_balance` is not a balance. The balance is the 8xxx chart account's,
 * derived from journal lines like every other balance here; this is the figure
 * the opening entry posted, kept so the Account Balance screen can show what an
 * account started with beside what it holds now.
 *
 * @property int $id
 * @property string $bank_name
 * @property string $account_number
 * @property string $account_name
 * @property AccountChannelType $account_type
 * @property AccountUsage $usage
 * @property int|null $bank_id
 * @property int|null $mobile_money_provider_id
 * @property string $account_number_key generated by the database
 * @property string $physical_account_key generated by the database
 * @property Currency $currency
 * @property string $opening_balance
 * @property string|null $description
 * @property int|null $chart_account_id
 * @property ActiveStatus $status
 */
class BankAccount extends Model
{
    use SoftDeletes;

    /** @var list<string> */
    /**
     * `account_number_key` and `physical_account_key` are deliberately ABSENT.
     * Both are generated by the database from `account_number` and the
     * provider, so nothing may assign them — see the 2026_09_06_000002
     * migration for what happened the one time a caller was expected to.
     *
     * @var list<string>
     */
    protected $fillable = [
        'account_type', 'usage', 'bank_name', 'bank_id', 'mobile_money_provider_id',
        'account_number', 'account_name', 'currency',
        'opening_balance', 'description', 'chart_account_id', 'status', 'created_by',
    ];

    /**
     * The institution this account is held with, from master data.
     *
     * `bank_name` survives beside it as the text an account was registered
     * under. A row whose text matches no bank in the list still reads
     * correctly, which matters for accounts registered before the list did.
     *
     * @return BelongsTo<Bank, $this>
     */
    public function bank(): BelongsTo
    {
        return $this->belongsTo(Bank::class, 'bank_id');
    }

    /** @return BelongsTo<MobileMoneyProvider, $this> */
    public function mobileMoneyProvider(): BelongsTo
    {
        return $this->belongsTo(MobileMoneyProvider::class, 'mobile_money_provider_id');
    }

    /**
     * How this account should be named in a selector — "NMB Bank — 2011098765400".
     *
     * Reads the provider from master data where it is set and falls back to the
     * stored text, so an account registered before the list existed still names
     * itself rather than showing a blank.
     */
    public function channelLabel(): string
    {
        $provider = match ($this->account_type) {
            AccountChannelType::Mno => $this->mobileMoneyProvider?->name,
            default => $this->bank?->name,
        } ?? $this->bank_name;

        return trim($provider) === ''
            ? $this->account_number
            : $provider.' — '.$this->account_number;
    }

    /**
     * Accounts that may RECEIVE money — collections and capital.
     *
     * Active only. An inactive account is one the company has stopped using,
     * and offering it in a selector invites a payment into an account nobody is
     * reconciling.
     *
     * @param Builder<$this> $query
     */
    public function scopeAcceptingInflow(Builder $query): void
    {
        $query->where('status', ActiveStatus::Active)
            ->whereIn('usage', [AccountUsage::Collection->value, AccountUsage::Both->value]);
    }

    /**
     * Accounts that may SEND money — disbursements and expenses.
     *
     * @param Builder<$this> $query
     */
    public function scopeAcceptingOutflow(Builder $query): void
    {
        $query->where('status', ActiveStatus::Active)
            ->whereIn('usage', [AccountUsage::Disbursement->value, AccountUsage::Both->value]);
    }

    /**
     * @return BelongsTo<ChartOfAccount, $this>
     */
    public function chartAccount(): BelongsTo
    {
        return $this->belongsTo(ChartOfAccount::class, 'chart_account_id');
    }

    /** @return BelongsTo<User, $this> */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * What the account holds now, from the ledger.
     *
     * Requires `chartAccount.balances` to be loaded. Returns zero for an
     * account whose chart row is missing, which cannot happen for a row this
     * application created — the two are made in one transaction — but can for
     * one seeded before that was true.
     */
    public function currentBalance(): Money
    {
        return $this->chartAccount?->cachedBalance() ?? Money::zero();
    }

    public function openingBalance(): Money
    {
        return Money::of($this->opening_balance);
    }

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'status' => ActiveStatus::class,
            'currency' => Currency::class,
            'account_type' => AccountChannelType::class,
            'usage' => AccountUsage::class,
            'opening_balance' => 'decimal:2',
        ];
    }
}
