<?php

namespace App\Http\Requests\Api\Payments;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Branch / teller non-cash receipt (POST /payments/branch-receipts): channel BANK or MNO with a bank or network from the company's
 * own list (Settings → Payment Channels), as on the Finance forms. The transaction ID and reference are generated by the system.
 * Cash keeps the teller cash + deposit slip flow.
 */
class BranchReceiptRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge(['channel' => strtoupper((string) $this->input('channel'))]);
    }

    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'loan_id' => ['required', 'integer', Rule::exists('loans', 'id')->where('company_id', $this->user()->company_id)],
            'amount' => ['required', 'numeric', 'min:1', 'max:9999999999999'],
            ...ConfirmedPaymentRequest::channelRules($this),
            'paid_on' => ['nullable', 'date', 'before_or_equal:today'],
            'note' => ['nullable', 'string', 'max:255'],
        ];
    }
}
