<?php

namespace App\Http\Requests\Api\Payments;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Finance-entered payment, single step (POST /payments/confirmed): the loan, amount, channel (BANK or MNO) with its provider,
 * and date; the transaction ID and reference are generated by the system. The money is received into the bank clearing account:
 * the provider is only a name, never one of the company's own bank accounts.
 */
class ConfirmedPaymentRequest extends FormRequest
{
    public const CHANNELS = ['BANK', 'MNO'];

    /**
     * Channel and provider rules shared with the unmatched-payment form: the provider must be an active bank or network of the
     * company's own list (Settings → Payment Channels) for that channel. The transaction ID and reference are generated by the
     * system, never typed.
     *
     * @return array<string, array<mixed>>
     */
    public static function channelRules(FormRequest $request): array
    {
        $channel = strtoupper((string) $request->input('channel'));

        return [
            'channel' => ['required', 'string', Rule::in(self::CHANNELS)],
            'provider' => ['required', 'string', 'max:100', Rule::exists('payment_providers', 'name')->where('company_id', $request->user()->company_id)->where('channel', $channel)->where('is_active', true)],
        ];
    }

    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'loan_id' => ['required', 'integer', Rule::exists('loans', 'id')->where('company_id', $this->user()->company_id)],
            'amount' => ['required', 'numeric', 'min:1', 'max:9999999999999'],
            ...self::channelRules($this),
            'paid_on' => ['required', 'date', 'before_or_equal:today'],
            'note' => ['nullable', 'string', 'max:255'],
        ];
    }
}
