<?php

namespace Tests\Feature\Api\Loans;

use App\Enums\Account;
use App\Enums\LoanStatus;
use App\Models\AuditLog;
use App\Models\Customer;
use App\Models\CustomerCategory;
use App\Models\Employee;
use App\Models\Loan;
use App\Models\LoanCategory;
use App\Services\Ledger;
use App\Services\LoanWorkflow;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Tests\Concerns\UploadsLoanAgreement;
use Tests\Concerns\UsesSecondApprover;
use Tests\TestCase;

/**
 * Loan agreement: generated by the system after branch manager approval, filled and signed by the customer, and the
 * signed copy uploaded before the credit officer can approve.
 */
class LoanAgreementApiTest extends TestCase
{
    use RefreshDatabase;
    use UploadsLoanAgreement;
    use UsesSecondApprover;

    private Employee $admin;

    private Customer $customer;

    private LoanCategory $category;

    protected function setUp(): void
    {
        parent::setUp();

        config(['integrations.vodacom.driver' => 'test', 'integrations.bank_mandate.driver' => 'test', 'integrations.vodacom.test_outcome' => 'success']);
        $this->admin = $this->signInAdmin();
        $this->grantSelfApproval($this->admin);
        $customerType = CustomerCategory::factory()->create(['company_id' => $this->admin->company_id]);
        $this->customer = Customer::factory()->create(['company_id' => $this->admin->company_id, 'branch_id' => $this->admin->branch_id, 'phone' => '255754000123', 'customer_category_id' => $customerType->id]);
        $this->category = LoanCategory::factory()->forCustomerType($customerType)->create(['insurance' => 0]);
        $this->category->branches()->attach($this->admin->branch_id);
        app(Ledger::class)->openingBalance($this->admin->company_id, Account::Principal, 1000000, 'FLOAT');
    }

    public function test_agreement_is_not_available_before_the_branch_manager_approves(): void
    {
        $loan = $this->applyLoan();

        $this->getJson(route('api.v1.loans.agreement.show', $loan))->assertUnprocessable()->assertJsonPath('errors.loan.0', LoanWorkflow::AGREEMENT_NOT_READY);
        $this->uploadAgreement($loan)->assertUnprocessable()->assertJsonPath('errors.attach.0', LoanWorkflow::AGREEMENT_NOT_READY);
        $this->getJson(route('api.v1.loans.show', $loan))->assertJsonPath('data.loan.agreement_available', false);
        $this->getJson(route('api.v1.loans.index', ['stage' => 'agreement']))->assertOk()->assertJsonCount(0, 'data');
    }

    public function test_manager_approval_generates_the_agreement_with_the_approved_terms(): void
    {
        $loan = $this->approvedLoan();

        $this->getJson(route('api.v1.loans.show', $loan))->assertJsonPath('data.loan.agreement_available', true);
        $this->getJson(route('api.v1.loans.index', ['stage' => 'agreement']))->assertOk()->assertJsonPath('data.0.loan_number', $loan->loan_number);
        $this->getJson(route('api.v1.loans.agreement.show', $loan))
            ->assertOk()
            ->assertJsonPath('data.agreement.number', 'MKT-'.$loan->loan_number)
            ->assertJsonPath('data.agreement.approved_by', $this->admin->full_name)
            ->assertJsonPath('data.agreement.uploaded_file', null)
            ->assertJsonPath('data.borrower.full_name', $this->customer->full_name)
            ->assertJsonPath('data.loan.amount', 100000)
            ->assertJsonPath('data.loan.instalments', 1)
            ->assertJsonPath('data.loan.total_payable', 130000)
            ->assertJsonCount(1, 'data.schedule')
            ->assertJsonPath('data.schedule.0.due_date', null);
    }

    public function test_credit_officer_cannot_approve_until_the_signed_agreement_is_uploaded(): void
    {
        $loan = $this->approvedLoan();
        $this->postJson(route('api.v1.loans.kyc-verify', $loan))->assertOk();

        $this->postJson(route('api.v1.loans.approve-credit', $loan))->assertUnprocessable()->assertJsonPath('errors.loan.0', LoanWorkflow::AGREEMENT_MISSING);
        $this->assertSame(LoanStatus::PendingCreditReview, $loan->fresh()->status);

        $this->uploadAgreement($loan)->assertOk()->assertJsonPath('message', 'Loan Agreement uploaded successfully');
        $loan->refresh();
        Storage::disk('public')->assertExists($loan->agreement_file);
        $this->assertSame($this->admin->id, $loan->agreement_uploaded_by);
        $this->assertNotNull($loan->agreement_uploaded_at);
        $this->assertTrue(AuditLog::where('auditable_id', $loan->id)->where('action', 'AGREEMENT_UPLOADED')->exists());

        $this->postJson(route('api.v1.loans.approve-credit', $loan))->assertOk();
        $this->assertSame(LoanStatus::PendingFinance, $loan->fresh()->status);
    }

    public function test_uploading_again_replaces_the_agreement(): void
    {
        $loan = $this->approvedLoan();
        $this->uploadAgreement($loan)->assertOk();
        $first = $loan->fresh()->agreement_file;

        $this->uploadAgreement($loan)->assertOk();

        $this->assertNotSame($first, $loan->fresh()->agreement_file);
        $this->assertTrue(AuditLog::where('auditable_id', $loan->id)->where('action', 'AGREEMENT_REPLACED')->exists());
        $this->getJson(route('api.v1.loans.agreement.show', $loan))->assertJsonPath('data.agreement.uploaded_by', $this->admin->full_name);
    }

    private function applyLoan(): Loan
    {
        $this->postJson(route('api.v1.loans.store'), [
            'customer_id' => $this->customer->id, 'category_id' => $this->category->id, 'how_loan' => 100000,
            'session' => 1, 'rate' => 'SIMPLE', 'fee_status' => 'YES', 'reason' => 'BIASHARA',
        ])->assertCreated();

        return Loan::latest('id')->firstOrFail();
    }

    private function approvedLoan(): Loan
    {
        $loan = $this->applyLoan();
        $this->postJson(route('api.v1.loans.approve-manager', $loan), ['loan_aprove' => 100000])->assertOk();

        return $loan->fresh();
    }
}
