<?php

namespace Tests\Feature\Api\Payments;

use App\Enums\Account;
use App\Enums\PaymentStatus;
use App\Models\BankAccount;
use App\Models\Employee;
use App\Models\JournalEntry;
use App\Models\Loan;
use App\Models\LoanTransaction;
use App\Models\Payment;
use App\Models\PaymentAllocation;
use App\Models\PaymentProvider;
use App\Models\TellerDeposit;
use App\Services\Ledger;
use App\Services\LoanService;
use App\Services\PaymentService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Concerns\UsesSecondApprover;
use Tests\Feature\Api\Loans\BuildsServiceLoans;
use Tests\TestCase;

/**
 * C6 payment flows: a Finance-entered payment is one step (ENTER → CONFIRMED → ALLOCATED → POSTED); a branch / teller non-cash
 * receipt is PENDING_APPROVAL and changes nothing until a different Finance user approves it; state changes are locked and
 * re-checked so duplicates post once.
 */
class FinanceAndBranchReceiptTest extends TestCase
{
    use BuildsServiceLoans;
    use InteractsWithRepayments;
    use RefreshDatabase;
    use UsesSecondApprover;

    private Employee $admin;

    protected function setUp(): void
    {
        parent::setUp();

        $this->admin = $this->signInAdmin();
        $this->admin->company->update(['reserve_percent' => 20]);
    }

    /**
     * The 100,000 / 30,000 active loan of {@see InteractsWithRepayments}, disbursed from the funded HQ PRINCIPAL A/C
     * (company level, no branch): a branch holds no lending money.
     */
    private function fundedLoan(): Loan
    {
        app(Ledger::class)->openingBalance($this->admin->company_id, Account::Principal, 100000, 'FLOAT');

        return $this->activeLoan($this->admin);
    }

    public function test_a_finance_payment_is_confirmed_allocated_and_posted_in_one_step(): void
    {
        $loan = $this->fundedLoan();
        $finance = $this->employeeWithRole($this->admin, 'finance');
        $bank = BankAccount::create(['company_id' => $this->admin->company_id, 'name' => 'NMB']);
        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'BANK', 'name' => 'NMB Bank']);
        $payload = ['loan_id' => $loan->id, 'amount' => 110000, 'channel' => 'BANK', 'provider' => 'NMB Bank', 'paid_on' => today()->toDateString()];

        $this->actingAs($this->employeeWithRole($this->admin, 'teller'))->postJson('/api/v1/payments/confirmed', $payload)->assertForbidden();
        $this->actingAs($finance)->postJson('/api/v1/payments/confirmed', $payload)->assertCreated()
            ->assertJsonPath('data.status', PaymentStatus::Allocated->value)
            ->assertJsonPath('data.allocated_amount', 110000);

        $payment = Payment::sole();
        $this->assertSame([$finance->id, $finance->id, Payment::SOURCE_MANUAL], [$payment->employee_id, $payment->verified_by, $payment->source]);
        $this->assertSame(['BANK', 'NMB Bank', null], [$payment->channel, $payment->provider, $payment->bank_account_id], 'a bank name only: received into bank clearing, never a company bank account');
        $this->assertMatchesRegularExpression('/^TX\d{6}[A-Z0-9]{10}$/', $payment->transaction_id, 'the transaction ID is generated by the system');
        $this->assertMatchesRegularExpression('/^PAY\d{6}[A-Z0-9]{6}$/', $payment->reference, 'the reference is generated by the system');
        $deposit = LoanTransaction::where('type', 'deposit')->sole();
        $this->assertEquals([100000, 10000, 2000], [$deposit->principal, $deposit->interest, $deposit->reserve]);
        $this->assertSame($deposit->id, PaymentAllocation::sole()->loan_transaction_id);
        $this->assertEquals(['principal' => 0, 'penalty' => 0, 'interest' => 20000, 'insurance' => 0, 'total' => 20000], app(LoanService::class)->outstanding($loan));
        $this->assertEquals([0, 0, 8000, 2000, 100000], [
            $this->balance($this->admin, Account::Suspense, $this->admin->branch_id),
            $this->balance($this->admin, Account::Bank, bankAccountId: $bank->id),
            $this->balance($this->admin, Account::InterestIncome, $this->admin->branch_id),
            $this->balance($this->admin, Account::InterestReserve, $this->admin->branch_id),
            $this->balance($this->admin, Account::Principal),
        ]);

        $entries = JournalEntry::count();
        $this->actingAs($finance)->postJson('/api/v1/payments/confirmed', ['amount' => 30000] + $payload)->assertUnprocessable()
            ->assertJsonValidationErrors(['amount' => 'Amount exceeds the outstanding balance of 20,000.']);
        $this->assertSame([$entries, 1], [JournalEntry::count(), Payment::count()], 'a rejected entry posts nothing');

        $headers = ['Idempotency-Key' => 'finance-payment-0001'];
        $replay = ['amount' => 5000] + $payload;
        $this->actingAs($finance)->postJson('/api/v1/payments/confirmed', $replay, $headers)->assertCreated();
        $this->actingAs($finance)->postJson('/api/v1/payments/confirmed', $replay, $headers)->assertCreated()->assertHeader('Idempotent-Replayed', 'true');
        $this->assertSame(2, Payment::count());
        $this->assertIntegrityPasses($this->admin);
    }

    public function test_a_finance_payment_channel_is_bank_or_mno_with_a_provider_from_the_company_list(): void
    {
        $loan = $this->fundedLoan();
        $finance = $this->employeeWithRole($this->admin, 'finance');
        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'BANK', 'name' => 'CRDB Bank']);
        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'MNO', 'name' => 'M-Pesa']);
        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'BANK', 'name' => 'Exim Bank', 'is_active' => false]);
        $payload = ['loan_id' => $loan->id, 'amount' => 1000, 'paid_on' => today()->toDateString()];
        $this->actingAs($finance);

        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'CASH', 'provider' => 'CRDB Bank'] + $payload)->assertUnprocessable()->assertJsonValidationErrors('channel');
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'BANK', 'provider' => 'M-Pesa'] + $payload)->assertUnprocessable()->assertJsonValidationErrors('provider');
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'MNO'] + $payload)->assertUnprocessable()->assertJsonValidationErrors('provider');
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'BANK', 'provider' => 'NBC Bank'] + $payload)->assertUnprocessable()->assertJsonValidationErrors('provider');
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'BANK', 'provider' => 'Exim Bank'] + $payload)->assertUnprocessable()->assertJsonValidationErrors('provider');
        $this->getJson('/api/v1/settings/payment-providers/options?channel=BANK')->assertOk()->assertExactJson(['data' => [['value' => 'CRDB Bank', 'label' => 'CRDB Bank']]]);

        $typed = ['transaction_id' => 'TYPED-1', 'reference' => 'TYPED-REF'];
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'MNO', 'provider' => 'M-Pesa'] + $typed + $payload)->assertCreated()->assertJsonPath('data.provider', 'M-Pesa');
        $this->postJson('/api/v1/payments/confirmed', ['channel' => 'MNO', 'provider' => 'M-Pesa'] + $typed + $payload)->assertCreated();

        $payments = Payment::orderBy('id')->get();
        $this->assertNotContains('TYPED-1', $payments->pluck('transaction_id'), 'a typed transaction ID is ignored');
        $this->assertNotContains('TYPED-REF', $payments->pluck('reference'), 'a typed reference is ignored');
        $this->assertCount(2, $payments->pluck('transaction_id')->unique(), 'every payment gets its own generated transaction ID');
    }

    public function test_a_branch_non_cash_receipt_changes_nothing_until_finance_approves_it(): void
    {
        $loan = $this->fundedLoan();
        $teller = $this->employeeWithRole($this->admin, 'teller');
        $finance = $this->employeeWithRole($this->admin, 'finance');
        $bank = BankAccount::create(['company_id' => $this->admin->company_id, 'name' => 'CRDB']);
        $entries = JournalEntry::count();
        $outstanding = app(LoanService::class)->outstanding($loan);

        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'MNO', 'name' => 'M-Pesa']);
        $this->actingAs($teller)->getJson('/api/v1/settings/payment-providers/options?channel=MNO')->assertOk()->assertJsonPath('data.0.value', 'M-Pesa');
        $receiptId = $this->actingAs($teller)->postJson('/api/v1/payments/branch-receipts', ['loan_id' => $loan->id, 'amount' => 50000, 'channel' => 'mno', 'provider' => 'M-Pesa', 'transaction_id' => 'TYPED-1'])->assertCreated()
            ->assertJsonPath('data.status', PaymentStatus::PendingApproval->value)->assertJsonPath('data.provider', 'M-Pesa')->json('data.id');
        $this->assertMatchesRegularExpression('/^TX\d{6}[A-Z0-9]{10}$/', Payment::find($receiptId)->transaction_id, 'the transaction ID is generated, a typed one is ignored');
        $this->actingAs($teller)->postJson('/api/v1/payments/branch-receipts', ['loan_id' => $loan->id, 'amount' => 1000, 'channel' => 'VODACOM'])->assertUnprocessable()->assertJsonValidationErrors(['channel', 'provider']);
        $this->actingAs($teller)->postJson('/api/v1/payments/branch-receipts', ['loan_id' => $loan->id, 'amount' => 80001, 'channel' => 'MNO', 'provider' => 'M-Pesa'])->assertUnprocessable()
            ->assertJsonValidationErrors(['amount' => 'Amount exceeds the balance still receivable of 80,000.']);
        $this->actingAs($teller)->postJson("/api/v1/teller/customers/{$loan->customer_id}/deposit", ['depost' => 80001, 'p_method' => 'CASH'])->assertUnprocessable()->assertJsonValidationErrors('depost');

        $this->assertSame($entries, JournalEntry::count(), 'a pending receipt posts no journal');
        $this->assertEquals($outstanding, app(LoanService::class)->outstanding($loan), 'the loan balance is unchanged before approval');
        $this->assertSame(0, LoanTransaction::where('type', 'deposit')->count());
        $this->assertEquals([0, 0], [$this->balance($this->admin, Account::InterestIncome, $this->admin->branch_id), $this->balance($this->admin, Account::Suspense, $this->admin->branch_id)]);

        $pending = app(PaymentService::class)->pendingBranchReceipts($this->admin->company_id);
        $this->assertSame([1, 50000.0, $receiptId], [$pending['count'], $pending['amount'], $pending['rows']->first()->id]);
        $this->actingAs($finance)->getJson('/api/v1/payments/branch-receipts')->assertOk()
            ->assertJsonPath('data.0.id', $receiptId)
            ->assertJsonPath('data.0.can_approve', true)
            ->assertJsonPath('pending_total', 50000);
        $this->actingAs($teller)->getJson('/api/v1/payments/branch-receipts')->assertOk()->assertJsonPath('data.0.can_approve', false);

        $this->actingAs($teller)->postJson("/api/v1/payments/branch-receipts/{$receiptId}/approve")->assertForbidden();
        $this->actingAs($finance)->postJson("/api/v1/payments/branch-receipts/{$receiptId}/approve", ['bank_account_id' => $bank->id])->assertOk()
            ->assertJsonPath('data.status', PaymentStatus::Allocated->value);
        $this->actingAs($finance)->postJson("/api/v1/payments/branch-receipts/{$receiptId}/approve")->assertUnprocessable();

        $this->assertEquals(['principal' => 50000, 'penalty' => 0, 'interest' => 30000, 'insurance' => 0, 'total' => 80000], app(LoanService::class)->outstanding($loan), 'changed after approval');
        $this->assertSame(1, LoanTransaction::where('type', 'deposit')->count());
        $this->assertEquals([0, 50000], [$this->balance($this->admin, Account::Bank, bankAccountId: $bank->id), $this->balance($this->admin, Account::Principal)]);
        $this->assertSame([$finance->id, $bank->id], [Payment::find($receiptId)->verified_by, Payment::find($receiptId)->bank_account_id]);
        $this->actingAs($this->admin);
        $this->assertIntegrityPasses($this->admin);
    }

    public function test_the_initiator_cannot_approve_or_reject_their_own_receipt_without_an_explicit_grant(): void
    {
        $loan = $this->fundedLoan();
        $url = '/api/v1/payments/branch-receipts';
        // Entered by Finance, who may also approve: rule 6 — not a permission — blocks the initiator (the Super Admin is exempt).
        $initiator = $this->employeeWithRole($this->admin, 'finance');
        $this->actingAs($initiator);
        PaymentProvider::create(['company_id' => $this->admin->company_id, 'channel' => 'MNO', 'name' => 'HaloPesa']);
        $first = $this->postJson($url, ['loan_id' => $loan->id, 'amount' => 1000, 'channel' => 'MNO', 'provider' => 'HaloPesa'])->assertCreated()->json('data.id');
        $second = $this->postJson($url, ['loan_id' => $loan->id, 'amount' => 2000, 'channel' => 'MNO', 'provider' => 'HaloPesa'])->assertCreated()->json('data.id');

        $this->getJson($url)->assertOk()->assertJsonPath('data.0.can_approve', false)
            ->assertJsonPath('data.0.approve_blocked_reason', 'You initiated this transaction, so another authorised user must approve it.');
        $this->postJson("{$url}/{$first}/approve")->assertForbidden();
        $this->postJson("{$url}/{$first}/reject", ['reason' => 'mine'])->assertForbidden();

        $this->asApprover($initiator, fn () => $this->postJson("{$url}/{$second}/reject", ['reason' => 'DEVFLOW wrong number'])->assertOk());
        $this->assertSame([PaymentStatus::Rejected, 'DEVFLOW wrong number'], [Payment::find($second)->status, Payment::find($second)->rejection_reason]);
        $this->assertNull(Payment::find($second)->journal_entry_id, 'a rejected receipt posted nothing');
        $this->asApprover($initiator, fn () => $this->postJson("{$url}/{$second}/approve")->assertUnprocessable());

        $this->grantSelfApproval($initiator);
        $this->postJson("{$url}/{$first}/approve")->assertOk();
        $this->assertSame(PaymentStatus::Allocated, Payment::find($first)->status);

        $outsider = $this->signInAdmin();
        $this->actingAs($outsider)->postJson("{$url}/{$second}/approve")->assertNotFound();
        $this->actingAs($outsider)->postJson($url, ['loan_id' => $loan->id, 'amount' => 1000, 'channel' => 'TIGO', 'transaction_id' => 'DEVFLOW-YAS-9'])->assertUnprocessable()->assertJsonValidationErrors('loan_id');
    }

    public function test_deposit_slips_and_suspense_actions_are_locked_and_re_checked(): void
    {
        $loan = $this->fundedLoan();
        $bank = BankAccount::create(['company_id' => $this->admin->company_id, 'name' => 'NMB']);
        // Banked by a Teller who may also verify: rule 6 — not a permission — blocks the depositor (the Super Admin is exempt).
        $depositor = $this->employeeWithRole($this->admin, 'teller');
        $depositor->permissionOverrides()->create(['permission' => 'payments.verify', 'granted' => true]);
        $this->actingAs($depositor->fresh());
        $this->postJson("/api/v1/teller/customers/{$loan->customer_id}/deposit", ['depost' => 10000, 'p_method' => 'CASH'])->assertCreated();
        $this->postJson('/api/v1/teller/bank-deposits', ['bank_account_id' => $bank->id, 'slip_number' => 'SLIP-L1', 'amount' => 10000, 'deposit_date' => today()->toDateString(), 'payment_ids' => [Payment::sole()->id]])->assertCreated();
        $deposit = TellerDeposit::sole();

        $this->postJson("/api/v1/payments/reconciliation/{$deposit->id}/reject", ['reason' => 'mine'])->assertForbidden();
        $this->asApprover($depositor, function (): void {
            $deposit = TellerDeposit::sole();
            $this->postJson("/api/v1/payments/reconciliation/{$deposit->id}/verify", ['statement_amount' => 10000, 'statement_reference' => 'NMB-9'])->assertOk();
            $this->postJson("/api/v1/payments/reconciliation/{$deposit->id}/confirm")->assertUnprocessable();
            $this->postJson("/api/v1/payments/reconciliation/{$deposit->id}/verify", ['statement_amount' => 10000, 'statement_reference' => 'NMB-9'])->assertUnprocessable();
            $this->postJson("/api/v1/payments/reconciliation/{$deposit->id}/reject", ['reason' => 'late'])->assertUnprocessable();
        });
        $this->assertSame(1, LoanTransaction::where('type', 'deposit')->count(), 'a double confirmation posts once');
        $this->actingAs($this->admin);

        $suspense = app(PaymentService::class)->recordUnmatched($this->admin->company_id, ['amount' => 7000, 'channel' => 'AIRTEL', 'transaction_id' => 'DEVFLOW-AT-7', 'paid_on' => today()->toDateString(), 'branch_id' => $this->admin->branch_id], $this->admin);
        $this->postJson("/api/v1/payments/suspense/{$suspense->id}/refund", ['reason' => 'DEVFLOW returned'])->assertOk();
        $this->postJson("/api/v1/payments/suspense/{$suspense->id}/refund", ['reason' => 'DEVFLOW again'])->assertUnprocessable();
        $this->postJson("/api/v1/payments/suspense/{$suspense->id}/flag", ['reason' => 'DEVFLOW'])->assertUnprocessable();
        $this->assertSame(1, JournalEntry::where('description', 'SUSPENSE REFUND '.$suspense->receipt_number)->count());
        $this->assertIntegrityPasses($this->admin);
    }
}
