<?php

namespace Tests\Feature\Api\Bank;

use App\Enums\Account;
use App\Models\BankTransfer;
use App\Models\Branch;
use App\Models\Employee;
use App\Models\ExpenseRequest;
use App\Models\ExpenseType;
use App\Services\Ledger;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Testing\TestResponse;
use Tests\Concerns\UsesSecondApprover;
use Tests\TestCase;

/**
 * Petty cash is the only money a branch holds: HQ sends it to one branch out of interest income, and the branch spends it
 * only on expenses HQ accepts (a water bill, stationery). Both steps are two-step (rule 6).
 */
class BranchPettyCashApiTest extends TestCase
{
    use RefreshDatabase;
    use UsesSecondApprover;

    private Employee $admin;

    private Employee $finance;

    private Ledger $ledger;

    private Branch $otherBranch;

    protected function setUp(): void
    {
        parent::setUp();

        $this->admin = $this->signInAdmin();
        $this->ledger = app(Ledger::class);
        $this->otherBranch = Branch::factory()->create(['company_id' => $this->admin->company_id]);
        $this->finance = $this->secondApprover($this->admin, 'finance');

        // Interest income earned by the two branches — what petty cash is funded from.
        $this->ledger->openingBalance($this->admin->company_id, Account::Interest, 300000, branch: $this->admin->branch_id);
        $this->ledger->openingBalance($this->admin->company_id, Account::Interest, 100000, branch: $this->otherBranch);
    }

    public function test_hq_sends_petty_cash_to_one_branch_out_of_interest_income_after_a_second_approval(): void
    {
        $companyId = $this->admin->company_id;

        $id = $this->sendPettyCash($this->admin->branch_id, 200000)
            ->assertCreated()->assertJsonPath('data.status', 'pending')->json('data.id');
        $this->assertMatchesRegularExpression('/^PC\d{6}[A-Z0-9]{6}$/', BankTransfer::findOrFail($id)->reference, 'the reference is generated by the system');
        $this->assertSame(0.0, $this->ledger->balance($companyId, Account::PettyCash, $this->admin->branch_id), 'a pending transfer moves nothing');

        $this->approveAsSecondUser($this->admin, "/api/v1/bank/transfers/{$id}/approve");

        $this->assertSame(200000.0, $this->ledger->balance($companyId, Account::PettyCash, $this->admin->branch_id));
        $this->assertSame(0.0, $this->ledger->balance($companyId, Account::PettyCash, $this->otherBranch->id), 'petty cash reaches the chosen branch only');
        $this->assertSame(200000.0, $this->ledger->balance($companyId, Account::Interest, allBranches: true), 'taken from the interest income of both branches');

        $this->getJson('/api/v1/bank/petty-cash?branch_id=all')->assertOk()
            ->assertJsonPath('hq_interest_balance', 200000)
            ->assertJsonPath('total', 200000)
            ->assertJsonPath('data.0.branch_account_label', 'PETTY CASH A/C');
        $this->getJson('/api/v1/dashboard')->assertOk()->assertJsonPath('data.today.expenses', 0);

        $this->postJson("/api/v1/bank/transfers/{$id}/reverse", ['reason' => 'Sent to the wrong branch'])->assertOk();
        $this->assertSame(0.0, $this->ledger->balance($companyId, Account::PettyCash, $this->admin->branch_id));
        $this->assertSame(400000.0, $this->ledger->balance($companyId, Account::Interest, allBranches: true));
    }

    public function test_more_than_the_hq_interest_income_cannot_be_sent(): void
    {
        $this->sendPettyCash($this->admin->branch_id, 400001)
            ->assertUnprocessable()->assertJsonValidationErrors('amount');

        $this->sendPettyCash(Branch::factory()->create()->id, 1000)
            ->assertUnprocessable()->assertJsonValidationErrors('branch_id');
    }

    public function test_head_office_is_not_a_branch_and_never_receives_petty_cash(): void
    {
        $hq = Branch::factory()->create(['company_id' => $this->admin->company_id, 'is_head_office' => true]);

        $ids = collect($this->getJson('/api/v1/bank/petty-cash?branch_id=all')->assertOk()->json('branches'))->pluck('id');
        $this->assertNotContains($hq->id, $ids);
        $this->assertContains($this->otherBranch->id, $ids);

        $this->sendPettyCash($hq->id, 1000)
            ->assertUnprocessable()->assertJsonValidationErrors('branch_id');
    }

    public function test_a_branch_expense_is_paid_from_its_petty_cash_and_never_more_than_it_holds(): void
    {
        $companyId = $this->admin->company_id;
        $branchId = $this->admin->branch_id;
        $id = $this->sendPettyCash($branchId, 50000)->assertCreated()->json('data.id');
        $this->approveAsSecondUser($this->admin, "/api/v1/bank/transfers/{$id}/approve");

        $type = ExpenseType::create(['company_id' => $companyId, 'scope' => 'branch', 'name' => 'WATER']);
        $water = fn (float $amount): ExpenseRequest => ExpenseRequest::create([
            'company_id' => $companyId, 'scope' => 'branch', 'branch_id' => $branchId, 'expense_type_id' => $type->id,
            'amount' => $amount, 'description' => 'water bill', 'status' => 'pending', 'request_date' => today(),
        ]);

        $requester = $this->secondApprover($this->admin, 'branch_manager');
        $tooMuch = $water(60000);
        $this->actingAs($requester)->postJson("/api/v1/expenses/requests/{$tooMuch->id}/accept", ['amount' => 60000])->assertForbidden();

        $this->actingAs($this->admin);
        $this->postJson("/api/v1/expenses/requests/{$tooMuch->id}/accept", ['amount' => 60000])
            ->assertUnprocessable()->assertJsonPath('errors.req_amount.0', 'Insufficient balance in PETTY CASH A/C');

        $bill = $water(12000);
        $this->postJson("/api/v1/expenses/requests/{$bill->id}/accept", ['amount' => 12000])->assertOk();

        $this->assertSame(38000.0, $this->ledger->balance($companyId, Account::PettyCash, $branchId));
        $this->assertSame(Account::PettyCash->value, $bill->fresh()->paid_from_account);
        $this->assertSame(12000.0, $this->ledger->balance($companyId, Account::OperatingExpense, $branchId));
    }

    /**
     * Sending petty cash is Finance's leg (funds.transfer); the owners only approve it, so the request is raised by a
     * Finance login and the signed-in Super Admin stays the approver.
     */
    private function sendPettyCash(int $branchId, float $amount): TestResponse
    {
        $response = $this->actingAs($this->finance)->postJson('/api/v1/bank/petty-cash', ['branch_id' => $branchId, 'amount' => $amount]);
        $this->actingAs($this->admin);

        return $response;
    }
}
